dist: trusty
language: c++
os:
  - linux
sudo: yes
compiler:
  - gcc

cache:
   directories:
     - $TRAVIS_BUILD_DIR/build/
     - $TRAVIS_BUILD_DIR/external/
stages:
    - analysis
    - build
    - test
    - push

jobs:
  include:
    - stage: analysis
      name: Static check the source code and lint 
      install:
        - sudo apt-get install -y cppcheck
        - sudo pip install --upgrade pip 
        - sudo pip install cpplint
      script:
          make lint
    - stage: build
      name: Build the kvrocks 
      script:
        - mkdir -p build
        - sudo apt-get install libsnappy-dev
        - make -j4
        - cp src/kvrocks build/kvrocks
    - stage: test 
      name: Unit Tests 
      script:
        - sudo apt-get install tar libsnappy-dev
        - wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz && tar -zxvf release-1.8.1.tar.gz
          && cd googletest-release-1.8.1/ && cmake CMakeLists.txt && make && sudo make install && cd -
        - make test
    - stage: test 
      name: Functional Tests
      install:
        - sudo pip install nose
        - sudo apt-get install libsnappy-dev
        - sudo pip install git+https://github.com/andymccurdy/redis-py.git@2.10.6
      script:
        - sh tests/scripts/setup-env.sh ./build 
        - cd tests/functional && nosetests -v
    - stage: push
      name: Push to dockerhub
      on:
        tags: true
      if: tag IS present
      services: 
        - docker
      before_install:  
        - docker build -t hulkdev/kvrocks:$TRAVIS_TAG .
        - docker tag hulkdev/kvrocks:$TRAVIS_TAG hulkdev/kvrocks:latest
      script: bash docker_push.sh
