# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

include_guard()

include(cmake/utils.cmake)

if ((${CMAKE_SYSTEM_NAME} MATCHES "Darwin") AND (NOT CMAKE_OSX_DEPLOYMENT_TARGET))
  set(SW_CMD "sw_vers")
  set(SW_CMD_ARG "-productVersion")
  execute_process(COMMAND ${SW_CMD} ${SW_CMD_ARG}
          WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
          OUTPUT_VARIABLE SW_CMD_OUTPUT
          RESULT_VARIABLE SW_CMD_STATUS
          OUTPUT_STRIP_TRAILING_WHITESPACE)
  if (SW_CMD_STATUS EQUAL 0)
    string(REGEX MATCH "[0-9]+.[0-9]+"
            DEPLOYMENT_TARGET ${SW_CMD_OUTPUT})
    set(CMAKE_OSX_DEPLOYMENT_TARGET "${DEPLOYMENT_TARGET}")
    message(STATUS "CMAKE_OSX_DEPLOYMENT_TARGET was set to: ${DEPLOYMENT_TARGET}")
  endif ()
endif ()

if ((${CMAKE_SYSTEM_NAME} MATCHES "Darwin") AND (NOT CMAKE_OSX_DEPLOYMENT_TARGET))
  message(FATAL_ERROR "The CMake option `CMAKE_OSX_DEPLOYMENT_TARGET` need to be specified, e.g. `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.3`")
endif ()

FetchContent_DeclareGitHubWithMirror(luajit
        RocksLabs/LuaJIT 02dfcc34e93e57ac96e566d123c66ee01e650299
        MD5=f1dd7a1bbf120b5a3daee71d896f5d08)

FetchContent_GetProperties(luajit)
if (NOT lua_POPULATED)
  FetchContent_Populate(luajit)

  # We use LUAJIT_CFLAGS instead of LUA_CFLAGS and we do not define LUA_ANSI.
  # LuaJIT relies heavily on architecture-specific assembly code and compiler optimization settings,
  # and LUA_ANSI is meant for standard Lua to restrict to ANSI C which LuaJIT does not support.
  set(LUAJIT_CFLAGS "-DENABLE_CJSON_GLOBAL -DREDIS_STATIC= -DLUA_USE_MKSTEMP -DLUAJIT_ENABLE_CHECKHOOK")
  set(LUAJIT_LDFLAGS "")
  if((CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang") OR
   (CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang"))
    set(LUAJIT_CFLAGS "${LUAJIT_CFLAGS} -isysroot ${CMAKE_OSX_SYSROOT}")
    set(LUAJIT_LDFLAGS "-isysroot ${CMAKE_OSX_SYSROOT}")
  endif ()

  if (CMAKE_HOST_APPLE)
    set(MACOSX_TARGET "MACOSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}")
  endif ()

  # We pass C compiler path CC and custom preprocessor definitions via XCFLAGS instead of CFLAGS.
  # Overriding CFLAGS on the make command line completely discards LuaJIT's own Makefile CFLAGS (such as
  # -O2 and target-specific compiler optimizations), which breaks the JIT compiler and assembler VM
  # stack unwinding on platforms like macOS arm64, leading to CPU spin locks or crashes.
  add_custom_target(make_luajit
    COMMAND ${MAKE_COMMAND} libluajit.a ${NINJA_MAKE_JOBS_FLAG}
      "CC=${CMAKE_C_COMPILER}" "XCFLAGS=${LUAJIT_CFLAGS}" "LDFLAGS=${LUAJIT_LDFLAGS}" "HOST_LDFLAGS=${LUAJIT_LDFLAGS}" ${MACOSX_TARGET}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${luajit_BINARY_DIR}/include
    COMMAND sh -c "cp ${luajit_SOURCE_DIR}/src/*.h ${luajit_SOURCE_DIR}/src/*.hpp ${luajit_BINARY_DIR}/include/"
    WORKING_DIRECTORY ${luajit_SOURCE_DIR}/src
    BYPRODUCTS ${luajit_SOURCE_DIR}/src/libluajit.a
  )

  file(GLOB LUA_PUBLIC_HEADERS "${luajit_SOURCE_DIR}/src/*.hpp" "${luajit_SOURCE_DIR}/src/*.h")
  file(COPY ${LUA_PUBLIC_HEADERS} DESTINATION ${luajit_BINARY_DIR}/include)
  # luajit.h is generated by LuaJIT's Makefile from luajit_rolling.h (host/genversion.lua
  # substitutes the ROLLING token with a git-derived version). Seed it at configure time
  # so tools that parse includes without building LuaJIT (e.g. clang-tidy) can resolve
  # `#include "luajit.h"` pulled in via lua.hpp. The real build overwrites this file.
  configure_file(${luajit_SOURCE_DIR}/src/luajit_rolling.h
    ${luajit_BINARY_DIR}/include/luajit.h COPYONLY)
endif()

add_library(luajit INTERFACE)
target_include_directories(luajit INTERFACE ${luajit_BINARY_DIR}/include)
target_link_libraries(luajit INTERFACE ${luajit_SOURCE_DIR}/src/libluajit.a dl)
add_dependencies(luajit make_luajit)
